// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: number-stream.proto

package com.groww.grpc.commons.stream;

public interface InputNumberOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InputNumber)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 number = 1;</code>
   * @return The number.
   */
  long getNumber();
}
