// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: number-stream.proto

package com.groww.grpc.commons.stream;

public final class NumberStreamProto {
  private NumberStreamProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InputNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InputNumber_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OutputNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OutputNumber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023number-stream.proto\"\035\n\013InputNumber\022\016\n\006" +
      "number\030\001 \001(\003\"\036\n\014OutputNumber\022\016\n\006number\030\001" +
      " \001(\0032Q\n\023NumberStreamService\022:\n\027streamInc" +
      "rementedNumber\022\014.InputNumber\032\r.OutputNum" +
      "ber\"\0000\001B4\n\035com.groww.grpc.commons.stream" +
      "B\021NumberStreamProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_InputNumber_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_InputNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InputNumber_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_OutputNumber_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OutputNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OutputNumber_descriptor,
        new java.lang.String[] { "Number", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
